# Generated by Django 4.2.6 on 2023-11-06 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name': 'VoteFields',
                'verbose_name_plural': 'VoteFields',
            },
        ),
        migrations.CreateModel(
            name='VoteForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=1000)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Open'), (2, 'Closed')], default=1)),
                ('closing', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'VoteForm',
                'verbose_name_plural': 'VoteForms',
            },
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='vote.voteform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='vote.votefields')),
            ],
            options={
                'verbose_name': 'Votes',
                'verbose_name_plural': 'Votes',
            },
        ),
        migrations.AddField(
            model_name='votefields',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_fields', to='vote.voteform'),
        ),
    ]
