# Generated by Django 4.2.6 on 2023-11-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteform',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
