# Generated by Django 4.2.6 on 2023-11-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_alter_votefields_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voteform',
            old_name='type',
            new_name='statistics_type',
        ),
        migrations.AddField(
            model_name='voteform',
            name='votes_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Single choice'), (2, 'Multiple choice')], default=1),
        ),
    ]
