# Generated by Django 4.2.6 on 2023-11-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_rename_type_voteform_statistics_type_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='voteform',
            constraint=models.CheckConstraint(check=models.Q(('closing__gt', models.F('created'))), name='closing_greater_than_created'),
        ),
    ]
