# Generated by Django 4.2.6 on 2023-11-24 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_voteform_closing_greater_than_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voteform',
            options={'ordering': ('-created',), 'verbose_name': 'VoteForm', 'verbose_name_plural': 'VoteForms'},
        ),
    ]
